REPAIR TABLE resolver_0 USE_FRM;
REPAIR TABLE resolver_1 USE_FRM;
REPAIR TABLE resolver_2 USE_FRM;
REPAIR TABLE resolver_3 USE_FRM;
REPAIR TABLE resolver_4 USE_FRM;
REPAIR TABLE resolver_5 USE_FRM;
REPAIR TABLE resolver_6 USE_FRM;
REPAIR TABLE resolver_7 USE_FRM;
REPAIR TABLE resolver_8 USE_FRM;
REPAIR TABLE resolver_9 USE_FRM;
REPAIR TABLE resolver_10 USE_FRM;
REPAIR TABLE resolver_11 USE_FRM;
REPAIR TABLE resolver_12 USE_FRM;
REPAIR TABLE resolver_13 USE_FRM;
REPAIR TABLE resolver_14 USE_FRM;
REPAIR TABLE resolver_15 USE_FRM;
REPAIR TABLE resolver_16 USE_FRM;
REPAIR TABLE resolver_17 USE_FRM;
REPAIR TABLE resolver_18 USE_FRM;
REPAIR TABLE resolver_19 USE_FRM;
REPAIR TABLE resolver_20 USE_FRM;
REPAIR TABLE resolver_21 USE_FRM;
REPAIR TABLE resolver_22 USE_FRM;
REPAIR TABLE resolver_23 USE_FRM;
REPAIR TABLE resolver_24 USE_FRM;
REPAIR TABLE resolver_25 USE_FRM;
REPAIR TABLE resolver_26 USE_FRM;
REPAIR TABLE resolver_27 USE_FRM;
REPAIR TABLE resolver_28 USE_FRM;
REPAIR TABLE resolver_29 USE_FRM;
REPAIR TABLE resolver_30 USE_FRM;
REPAIR TABLE resolver_31 USE_FRM;

ALTER TABLE  resolver_0 ENABLE KEYS;
ALTER TABLE  resolver_1 ENABLE KEYS;
ALTER TABLE  resolver_2 ENABLE KEYS;
ALTER TABLE  resolver_3 ENABLE KEYS;
ALTER TABLE  resolver_4 ENABLE KEYS;
ALTER TABLE  resolver_5 ENABLE KEYS;
ALTER TABLE  resolver_6 ENABLE KEYS;
ALTER TABLE  resolver_7 ENABLE KEYS;
ALTER TABLE  resolver_8 ENABLE KEYS;
ALTER TABLE  resolver_9 ENABLE KEYS;
ALTER TABLE  resolver_10 ENABLE KEYS;
ALTER TABLE  resolver_11 ENABLE KEYS;
ALTER TABLE  resolver_12 ENABLE KEYS;
ALTER TABLE  resolver_13 ENABLE KEYS;
ALTER TABLE  resolver_14 ENABLE KEYS;
ALTER TABLE  resolver_15 ENABLE KEYS;
ALTER TABLE  resolver_16 ENABLE KEYS;
ALTER TABLE  resolver_17 ENABLE KEYS;
ALTER TABLE  resolver_18 ENABLE KEYS;
ALTER TABLE  resolver_19 ENABLE KEYS;
ALTER TABLE  resolver_20 ENABLE KEYS;
ALTER TABLE  resolver_21 ENABLE KEYS;
ALTER TABLE  resolver_22 ENABLE KEYS;
ALTER TABLE  resolver_23 ENABLE KEYS;
ALTER TABLE  resolver_24 ENABLE KEYS;
ALTER TABLE  resolver_25 ENABLE KEYS;
ALTER TABLE  resolver_26 ENABLE KEYS;
ALTER TABLE  resolver_27 ENABLE KEYS;
ALTER TABLE  resolver_28 ENABLE KEYS;
ALTER TABLE  resolver_29 ENABLE KEYS;
ALTER TABLE  resolver_30 ENABLE KEYS;
ALTER TABLE  resolver_31 ENABLE KEYS;

/** Load Index into memory */
load index into cache resolver_0;
load index into cache resolver_1;
load index into cache resolver_2;
load index into cache resolver_3;
load index into cache resolver_4;
load index into cache resolver_5;
load index into cache resolver_6;
load index into cache resolver_7;
load index into cache resolver_8;
load index into cache resolver_9;
load index into cache resolver_10;
load index into cache resolver_11;
load index into cache resolver_12;
load index into cache resolver_13;
load index into cache resolver_14;
load index into cache resolver_15;
load index into cache resolver_16;
load index into cache resolver_17;
load index into cache resolver_18;
load index into cache resolver_19;
load index into cache resolver_20;
load index into cache resolver_21;
load index into cache resolver_22;
load index into cache resolver_23;
load index into cache resolver_24;
load index into cache resolver_25;
load index into cache resolver_26;
load index into cache resolver_27;
load index into cache resolver_28;
load index into cache resolver_29;
load index into cache resolver_30;
load index into cache resolver_31;